### ISSUE TITLE
Going full screen causes chewieController to be disposed()

### ISSUE THREAD

**Issue by RollyPeres** [brianegan/chewie#140]
Hi Brian,

I have a tab page with a button among others. When I tap this button I want to navigate to a page where I would like to show a picture or a video. Everything works fine, I can navigate back and forward and see any photo/video I load. But whenever I press the full screen button on the chewie player an error is thrown saying the chewieController was disposed() and therefore cannot be used anymore.

So on the tap of a button from a tab page I do this:
```
Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => MediaViewer(
                mimeType: estimateAttachment.fileMimeType, // This is photo or video.
                content: estimateAttachment.fileContent, // This is Uint8List
              )
            ),
          );
```

The page I'm navigating to looks like: 

```

class MediaViewer extends StatelessWidget {
  MediaViewer({
    @required this.mimeType,
    @required this.content
  }): assert(mimeType != null),
      assert(content != null);

  final MimeType mimeType;
  final Uint8List content;

 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: true,
        iconTheme: IconThemeData(color: Colors.white),
        backgroundColor: Theme.of(context).primaryColorLight,
        title: Text(_calcAlertTitle),
      ),
      body: Container(
        child: _buildViewer
      ),
    );
  }

  String get _calcAlertTitle {
    switch (mimeType) {
      case MimeType.Image:
        return 'Document deviz';

      case MimeType.Video:
        return 'Video deviz';

      default:
        return 'TODO: not implemented.';
    }
  }

  Widget get _buildViewer {

    if (content == null ||
        content.length == 0) {
      return const NoContent();
    }

    switch (mimeType) {
      case MimeType.Image:
        return _photoViewer;

      case MimeType.Video:
        return _videoViewer;

      default:
        return Center(
          child: mimeType != MimeType.Unknown 
                  ? Text('TODO: viewer not implemented for mimeType $mimeType.')
                  : NoContent(),
        );
    }
  }

  Widget get _photoViewer => _buildContent(
    contentWidget: Image.memory(
      content,
      fit: BoxFit.fill,
    ),
  );

  Widget get _videoViewer => FutureBuilder(
    future: MediaHelper.saveVideoToDevice(bytes: content),
    builder: (context, AsyncSnapshot<String> snap) {
      switch (snap.connectionState) {
        case ConnectionState.none:
        case ConnectionState.waiting:
        case ConnectionState.active:
          return ProgressBarWidget();

        case ConnectionState.done:

          if (!snap.hasData || snap.hasError) {
            return NoContent();
          }

          return VideoPlayerViewer(
            videoPath: snap.data,
          );
      }
    },
  );

  Widget _buildContent({@required Widget contentWidget}) => contentWidget != null ? contentWidget : const NoContent();
}

```

And finally the video player viewer looks like: 

```
class VideoPlayerViewer extends StatefulWidget {

  VideoPlayerViewer({ @required this.videoPath });

  final String videoPath;

  @override
  _VideoPlayerViewerState createState() => _VideoPlayerViewerState();
}

class _VideoPlayerViewerState extends State<VideoPlayerViewer> {
 VideoPlayerController _videoPlayerController;
  ChewieController _chewieController;

  @override
  void initState() {
    super.initState();

    try {
      File file = File.fromUri(Uri(path: widget.videoPath));

      _videoPlayerController = VideoPlayerController.file(file);

      _chewieController = ChewieController(
        videoPlayerController: _videoPlayerController,
        aspectRatio: 1 / 1,
        autoPlay: true,
        looping: true,
        allowFullScreen: true
      );
    } catch (e) {
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child:  Chewie(
        controller: _chewieController,
      ),
    );
  }

  @override
  void dispose() {
    logInfo('dispose()', type: runtimeType);
    _chewieController?.dispose();
    _videoPlayerController?.dispose();
    super.dispose();
  }
}
```

When on the VideoPlayerViewer and when pressing the full screen button I get the error I mentioned earlier. The stack trace when error occurs looks like this:

```
I/flutter ( 8811): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 8811): The following assertion was thrown while handling a gesture:
I/flutter ( 8811): A ChewieController was used after being disposed.
I/flutter ( 8811): Once you have called dispose() on a ChewieController, it can no longer be used.
I/flutter ( 8811): 
I/flutter ( 8811): When the exception was thrown, this was the stack:
I/flutter ( 8811): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
package:flutter/…/foundation/change_notifier.dart:105
I/flutter ( 8811): #1      ChangeNotifier._debugAssertNotDisposed 
package:flutter/…/foundation/change_notifier.dart:111
I/flutter ( 8811): #2      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:200
I/flutter ( 8811): #3      ChewieController.toggleFullScreen 
package:chewie/src/chewie_player.dart:325
I/flutter ( 8811): #4      _MaterialControlsState._onExpandCollapse.<anonymous closure> 
package:chewie/src/material_controls.dart:300
I/flutter ( 8811): #5      State.setState 
package:flutter/…/widgets/framework.dart:1122
I/flutter ( 8811): #6      _MaterialControlsState._onExpandCollapse 
package:chewie/src/material_controls.dart:297
I/flutter ( 8811): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:120
I/flutter ( 8811): #8      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:242
I/flutter ( 8811): #9      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:204
I/flutter ( 8811): #10     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
I/flutter ( 8811): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
I/flutter ( 8811): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:192
I/flutter ( 8811): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:149
I/flutter ( 8811): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:101
I/flutter ( 8811): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:85
I/flutter ( 8811): #19     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter ( 8811): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter ( 8811): (elided 3 frames from package dart:async)
I/flutter ( 8811): 
I/flutter ( 8811): Handler: onTap
I/flutter ( 8811): Recognizer:
I/flutter ( 8811):   TapGestureRecognizer#05ede(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter ( 8811):   Offset(800.3, 388.9), sent tap down)
I/flutter ( 8811): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
Thanks for your time!

**Comment by aaron3481** [comment]
I have the same issue

**Comment by sarbjeetromana** [comment]
I solve this issues in my application .
Actually i was doing the _controller.dispose() and _chewiecontroller.dispose() on pressing on back button and after that when i click on back button show exception :

I/flutter ( 8811): A ChewieController was used after being disposed.
I/flutter ( 8811): Once you have called dispose() on a ChewieController, it can no longer be used.


and i remove that and both controller dispose in dispose method and now working for my application very well .



import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:video_player/video_player.dart';

class FullScreenVideo extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
  
    return FullScreenVideoo();
  }
}

class FullScreenVideoo extends StatefulWidget {


  @override
  State<StatefulWidget> createState() {

    return _FullScreenVideo();
  }
}

class _FullScreenVideo extends State<FullScreenVideoo> {
  static const _rotationChannel = const MethodChannel('zgadula/orientation');

  VideoPlayerController _controller;
  ChewieController _chewieController;
  Future<void> _initializeVideoPlayerFuture;

  

  @override
  void initState() {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,

    ]);
    try {
      _rotationChannel.invokeMethod('setLandscape');
    } catch (error) {}

      _controller = VideoPlayerController.network(
        'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      );
    _initializeVideoPlayerFuture = _controller.initialize();
    _chewieController = ChewieController(
      videoPlayerController: _controller,
      aspectRatio: 16 / 9,
      fullScreenByDefault: false,
      allowFullScreen: false,
      looping: true,
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,

    ]);
    try {
      _rotationChannel.invokeMethod('setLandscape');
    } catch (error) {}

    Size size = MediaQuery.of(context).size;
    var TOPBAR_CONTAINERHEIGHT = size.height * 0.15;

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(

        body: Container(child:  Stack(
          children: <Widget>[
            Container(
              child: FutureBuilder(
                future: _initializeVideoPlayerFuture,
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.done) {
                    // If the VideoPlayerController has finished initialization, use
                    // the data it provides to limit the aspect ratio of the video.
                    return Container(
                      // Use the VideoPlayer widget to display the video.
                      child: Chewie(
                        controller: _chewieController,
                      ),
                    );
                  } else {
                    // If the VideoPlayerController is still initializing, show a
                    // loading spinner.
                    return Center(child: CircularProgressIndicator());
                  }
                },
              ),
            ),
            Container(
                height: TOPBAR_CONTAINERHEIGHT,
                alignment: Alignment.bottomLeft,
                margin: EdgeInsets.only(left: 5),
                child: InkWell(
                  child: Image.asset(
                    'assets/images/ic_back.png',
                    width: TOPBAR_CONTAINERHEIGHT / 2,
                    height: TOPBAR_CONTAINERHEIGHT / 2,
                  ),
                  onTap: ()  {

                    Navigator.pop(context,true);

                  },
                )),
          ],
        ),),
      ),
      );
  }

  void disposecontroller(){


    _chewieController.dispose();
    _controller.dispose();
    try {
      _rotationChannel.invokeMethod('setPortrait');
    } catch (error) {
      print("print ${error}");
    }
  }

  @override
  void dispose() {
    print("print dispose");
    disposecontroller();
    super.dispose();
  }
}


this my code


I hope this helpfull for someone.
Happy Coding.........
