### ISSUE TITLE
No video player associated with texture id xx

### ISSUE THREAD

**Issue by zxzxzxygithub** [brianegan/chewie#148]
after I call  controller.dispose,it shows an error below:
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Unknown textureId, No video player associated with texture id 61, null)
E/flutter ( 3537): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 3537): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 3537): <asynchronous suspension>
E/flutter ( 3537): #2      VideoPlayerController.position (package:video_player/video_player.dart:388:36)

**Comment by nandawperdana** [comment]
hi @zxzxzxygithub any update on this? thank you
