### ISSUE TITLE
Video player throws error when put in ListView and scrolled past really quickly

### ISSUE THREAD

**Issue by nathanfletcher** [brianegan/chewie#21]
When the video is part of a list and you scroll to it very quickly, it throws an error and the interface becomes red.

Code to reproduce:
```
import 'package:flutter/material.dart';
import 'package:chewie/chewie.dart';
import 'package:video_player/video_player.dart';


class Media extends StatefulWidget {
  @override
  MediaState createState() {
    return new MediaState();
  }
}

class MediaState extends State<Media> {
  VideoPlayerController _controller;


  @override
  void initState() {
    super.initState();
    _controller = new VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/videos/butterfly.mp4',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Media"),
        actions: <Widget>[],
      ),
      //TODO: Add a grid view (102)
      body: new ListView(
        children: <Widget>[
          Chewie(
            _controller,
            aspectRatio: 1280 / 720,
            autoPlay: false,
            looping: false,
          ),
          new Column(
            children: List.generate(20, (index) {
              return feedCard();
            }),
          ),
        ],
      ),
    );
  }

  Widget feedCard() {
    return new Card(
      child: new Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          ListTile(
            leading: Icon(Icons.ondemand_video),
            title: Text('The Enchanted Nightingale',
                style: TextStyle(fontWeight: FontWeight.bold)),
            subtitle: Column(
              children: <Widget>[
                Text('Video by Julie Gable. Lyrics by Sidney Stein.'),
                Align(
                  alignment: Alignment.bottomLeft,
                  child: Text('Sunday 5th July, 2020',
                      style: TextStyle(fontStyle: FontStyle.italic)),
                ),
              ],
            ),
          ),
          new ButtonTheme.bar(
            // make buttons use the appropriate styles for cards
            child: new ButtonBar(
              children: <Widget>[
                new FlatButton(
                  child: const Text('Download'),
                  onPressed: () {/* ... */},
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

```

```
I/flutter ( 6193): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6193): The following assertion was thrown building Chewie(state: _ChewiePlayerState#17748):
I/flutter ( 6193): A VideoPlayerController was used after being disposed.
I/flutter ( 6193): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter ( 6193): When the exception was thrown, this was the stack:
I/flutter ( 6193): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
I/flutter ( 6193): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
I/flutter ( 6193): #2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:97:12)
I/flutter ( 6193): #3      _VideoPlayerWithControlsState.initState (package:chewie/src/player_with_controls.dart:114:23)
I/flutter ( 6193): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
I/flutter ( 6193): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 6193): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 6193): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 6193): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 6193): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 6193): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 6193): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 6193): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 6193): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 6193): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 6193): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 6193): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 6193): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 6193): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 6193): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 6193): #28     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter ( 6193): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 6193): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 6193): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 6193): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 6193): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 6193): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 6193): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 6193): #38     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter ( 6193): #39     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
I/flutter ( 6193): #40     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 6193): #41     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter ( 6193): #42     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter ( 6193): #43     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter ( 6193): #44     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter ( 6193): #45     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter ( 6193): #46     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter ( 6193): #47     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:352:5)
I/flutter ( 6193): #48     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:99:29)
I/flutter ( 6193): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 6193): #50     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 6193): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 6193): #52     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter ( 6193): #53     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1131:12)
I/flutter ( 6193): #54     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1049:20)
I/flutter ( 6193): #55     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 6193): #56     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 6193): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 6193): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 6193): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 6193): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6193): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6193): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6193): #63     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 6193): #64     _drawFrame (dart:ui/hooks.dart:109:3)
```

**Comment by brianegan** [comment]
Thanks! This is a bit of a tricky one, but I think I know where the bug is. I'll try to push up a fix for it over the weekend :)

**Comment by fukemy** [comment]
Yeah i just face this problem. Used chewie in listview and hero animation then got same problem here. Plz take a look for my problem.
https://www.facebook.com/groups/425920117856409/permalink/445629875885433/?comment_id=445945799187174&reply_comment_id=445947905853630&notif_id=1528354334487283&notif_t=group_comment
 THanks you

**Comment by fukemy** [comment]
Hi. I changed code to 
```
child: new VideoPlayer(_videoController),
```
then no problem. Only red screen when using chewie. Plz fix that

**Comment by cbenhagen** [comment]
Can't reproduce this issue in `Chewie` 1.0.0. If the issue should persist after updating to 1.0.0 (Use my branch from #99 if not released yet.) please comment and I will reopen the issue.

**Comment by SameerDonga** [comment]
Hello, 

I have tried to implement this inside my Listview widget and I have tried version 0.9.0 as well in 0.9.4 but I got the same issue(Black screen). In my code I just initialize video and i don't want to play it but on click of that I am opening another view and inside that, I play the video. 

This is a snippet of my code: 
`VideoPlayerController _videoPlayerController =
              VideoPlayerController.network(mediaModel.path);
          final _chewieController = ChewieController(
              videoPlayerController: _videoPlayerController,
              autoPlay: false,
              looping: false,
              aspectRatio: 1,
              showControls: false,
              autoInitialize: true,
              overlay: Center(
                child: InkWell(
                  onTap: () {
                    goToMediaFullScreen(context, mediaModel);
                  },
                  child: Icon(
                    Icons.play_circle_outline,
                    color: Colors.grey,
                    size: 50,
                  ),
                ),
              ));

          mediaChildWidget.add(Chewie(
            controller: _chewieController,
          ));
`

Please help.

**Comment by klaszlo8207** [comment]
Any new on this? I get a lot of 

"Another exception was thrown: A ChewieController was used after being disposed."

when I try to play a video from a gridview click...

**Comment by AriCohen8** [comment]
I am having this issue using version ^0.9.8+1. Can this be reopened?

void initState() {
    super.initState();
    _chewieController = ChewieController(
      videoPlayerController: widget.videoPlayerController,
      aspectRatio: 3/4,
      autoInitialize: true,
      looping: widget.looping,
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
  }

**Comment by AriCohen8** [comment]
Update: I changed the logic so that the videocontroller was not passed from the stateful widget and instead passed a file path. Initstate then assigned the videocontroller from widget.videoPath. This worked!

**Comment by AriCohen8** [comment]
This link solved my issue - I needed to move a super.dispose() line to after the chewie.dispose() in my override void dispose area.
https://github.com/brianegan/chewie/issues/170

**Comment by GelidGeorge** [comment]
I set the auto dispose parameter to false and dispose it when ever I am off the page...
