### ISSUE TITLE
使用列表播放多个视频插件奔溃问题 Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.

### ISSUE THREAD

**Issue by mcxinyu** [brianegan/chewie#223]
我在列表中创建多个video_player对象，但是好像到一定数量的时候就奔溃了，后面和前面的视频都无法播放了。

Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.

Failed to initialize decoder: OMX.qcom.video.decoder.avc
android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1670)
	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)

请问大家有遇到么？
我在网站查了一下，[这个博客](https://blog.csdn.net/look_up_at/article/details/99864814)说是没有释放对象导致的。
应该怎么解决了？

**Comment by cbenhagen** [comment]
`Chewie` is only a GUI layer on top of the official `video_player` plugin. I don't think there is anything for us to do here so I am closing this. Please open an issue for the `video_player` plugin on https://github.com/flutter/flutter/issues.
