### ISSUE TITLE
Error when launch this project

### ISSUE THREAD

**Issue by tmp05** [brianegan/chewie#288]
Copy the project from github and her errors like:
E/flutter ( 9212): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter ( 9212): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:289)
E/flutter ( 9212): 
F/flutter ( 9212): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(123)] Check failed: CheckException(env). 
E/flutter ( 9570): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter ( 9570): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:289)

**Comment by Ahmadre** [comment]
Example App is fixed. Raise and follow this PR: https://github.com/brianegan/chewie/pull/289 for more infos.
