### ISSUE TITLE
ExoPlaybackException Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1]), null)

### ISSUE THREAD

**Issue by samiissa** [brianegan/chewie#293]
Flutter info:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓]  Flutter (Channel master, v1.16.4-pre.69, on Mac OS X 10.14.5 18F132, locale en-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
```
Chewie version: 
```
chewie: ^0.9.7
```

I'm developing an app with Flutter to play videos sequentially. In **Android**, after play a random number of times the same video, app crash with this error (_iOS not tested_):

```
Playback error.
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1])
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1])
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
... 9 more
Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1811)
	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1792)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
	... 10 more
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1]), null)
```

This is the UI logic to load the Chewei Widget:

```
class SliderScreen extends StatefulWidget {
  static String id = 'SliderScreen';

  @override
  _SliderScreenState createState() => _SliderScreenState();
}

class _SliderScreenState extends State<SliderScreen> {
  SliderViewModel vModel;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    if (null != vModel) vModel.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BaseView<SliderViewModel>(
        onModelReady: (model) {
          model.downloadController = locator<DownloadController>();
          model.downloadController.init(callback: model.onFirstFileDownloaded);

          vModel = model;

          vModel.getSlots(isFirstCall: true);
        },
        builder: (context, model, child) => null != model.medias && model.medias.length > 0
            ? FutureBuilder(
                future: model.initializeVideoPlayerFuture,
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.done) {
                    vModel.chewieController.play();

                    return AspectRatio(
                        aspectRatio: 16 / 9,
                        // Use the VideoPlayer widget to display the video.
                        child: Center(
                          child: null != vModel.chewieController ? Chewie(controller: vModel.chewieController) : Center(child: CircularProgressIndicator()),
                        ));
                  } else {
                    return SizedBox(
                      height: 300,
                      child: Center(child: CircularProgressIndicator()),
                    );
                  }
                })
            : SizedBox());
  }
}
```

And the viewModel where is the download and play the medias.

```
class SliderViewModel extends BaseViewModel {
  static String id = 'SliderViewModel';
  static int kFiveMinutes = 5 * 60;

  Slot currentSlot;
  Slot nextSlot;

  DownloadController downloadController;
  Timer nextSlotTimer;

  List<TaskInfo> medias = [];

  VideoPlayerController videoController;
  ChewieController chewieController;

  bool _disposed = false;
  var _isPlaying = false;
  var _isEndPlaying = false;
  var _canPlay = true;
  String token;
  int currentIndex = 0;

  Future<void> initializeVideoPlayerFuture;

  void getSlots({bool isFirstCall = false}) async {
    //get videos to show.....
  }

  void addToDownload({Slot slot, bool resetMedias = false}) async {
    if (resetMedias) {
      medias.clear();

      downloadController.clearTasks();
      await downloadController.cancelDownload();
    }

    await downloadController.addMediasToDownload(ads: slot.ads, slotStart: slot.slot.sta);
    downloadController.startDownloadMedias();
  }

  Future<void> _startPlay() async {
    print("play ---------> ${medias[currentIndex].path}");
    initializeVideoPlayerFuture = null;

    Future.delayed(const Duration(milliseconds: 200), () {
      _clearPrevious().then((_) {
        _initializePlay();
      });
    });
  }

  Future<void> _initializePlay() async {
    print('*****************      preparing ${medias[currentIndex].path}');

    videoController = VideoPlayerController.file(File(medias[currentIndex].path));

    videoController.addListener(_controllerListener);

    chewieController = ChewieController(
      videoPlayerController: videoController,
      aspectRatio: 16 / 9,
      fullScreenByDefault: true,
      showControls: true,
      autoPlay: true,
      // Prepare the video to be played and display the first frame
      autoInitialize: true,
      looping: false,
      // Errors can occur for example when trying to play a video
      // from a non-existent URL
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
    //chewieController.addListener(_controllerListener);

    initializeVideoPlayerFuture = videoController.initialize();
    setState(ViewState.Idle);
  }

  Future<bool> _clearPrevious() async {
    await videoController?.pause();
    videoController?.removeListener(_controllerListener);
    await videoController?.dispose();
    return true;
  }

  void onFirstFileDownloaded(TaskInfo task) {
    if (null != task) {
      print('current slot: ${currentSlot.slot.sta} - task slot: ${task.slotStart} - ${task.name} FINISH!!!');

      if (currentSlot.slot.sta == task.slotStart) {
        medias.add(task);

        if (!_isPlaying) {
          if (_canPlay) {
            loadNextMedia();

            _canPlay = false;
          }
        }
      }
    } else
      print('all files downloaded!!!');
  }

  Future<void> _controllerListener() async {
    if (videoController == null || _disposed) {
      return;
    }
    if (!videoController.value.initialized) {
      return;
    }
    final position = await videoController.position;
    final duration = videoController.value.duration;
    final isPlaying = position.inMilliseconds < duration.inMilliseconds;
    final isEndPlaying = position.inMilliseconds > 0 && position.inSeconds == duration.inSeconds;

    if (_isPlaying != isPlaying || _isEndPlaying != isEndPlaying) {
      _isPlaying = isPlaying;
      _isEndPlaying = isEndPlaying;

      print(" -----> isPlaying=$isPlaying");
      if (!_isPlaying) {
        //mark media as viewed
        print('send viewed ${medias[currentIndex].ad.id}');
        apiServices.sendViewed(
            token: token,
            adId: medias[currentIndex].ad.id.toString(),
            userId: await AppSingleton().storage.read(key: kUserId),
            slotId: currentSlot.slot.tsi.toString(),
            def: medias[currentIndex].ad.def.toString());

        final isComplete = medias.length - 1 == currentIndex;

        if (isComplete) {
          print("played all!!");

          if (currentSlot.slot.loop == 0 || currentSlot.slot.loop == 1 && medias[currentIndex].ad.def == 0) medias.removeAt(currentIndex);

          currentIndex = 0;

          if (currentSlot.slot.loop == 1) loadNextMedia();

          setState(ViewState.Idle);
        } else {
          _canPlay = true;

          print('finish play ${medias[currentIndex].name} - slot: ${medias[currentIndex].slotStart}');

          if (currentSlot.slot.loop == 0 || (currentSlot.slot.loop == 1 && medias[currentIndex].ad.def == 0))
            medias.removeAt(currentIndex);
          else
            currentIndex++;

          if (medias.length > currentIndex)
            loadNextMedia();
          else
            setState(ViewState.Idle);
        }
      }
    }
  }

  void loadNextMedia() {
      _startPlay();
  }

  @override
  void dispose() {
    _disposed = true;
    videoController.dispose();
    chewieController.dispose();
    initializeVideoPlayerFuture = null;
    super.dispose();
  }
}
```

I need some suggestions to solve it. I've spent 4 days with this problem with no luck.

Thanks.

**Comment by jhomlala** [comment]
I've seen similar errors in my app. It's connected to maximal amount of videos that can be handled by exo player. Your device has limited memory and exo player can't load next video.

**Comment by Silerqin** [comment]
I faced this error also. I get error `Video player had error c.b.a.a.h: c.b.a.a.n0.b$a: Decoded failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [400, 400, -1.0], [-1, -1])`. Can I know how to solve it?

**Comment by jhomlala** [comment]
Please try using Better Player. https://github.com/jhomlala/betterplayer Recently, I've added support for reusable videos, so this problem should be fixed.

**Comment by RoyWaqasAzeem** [comment]
Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1]), null, null)

**Comment by nstrelow** [comment]
This is a video_player problem.

@jhomlala How can better player help there? If it can, the please try that.

**Comment by KingAlawaka** [comment]
Any solution to this problem? I have a video timeline and some of the videos working fine and some of the videos are throwing this error.
Thanks in advance
