### ISSUE TITLE
Unable to play video from HTTP source on Android Platform.

### ISSUE THREAD

**Issue by swapnilshah09** [brianegan/chewie#303]
Here is the code snippet:
```
@override
  void initState() {
    super.initState();
    print('------course details-----');
    print(widget.courseDetails);
    videoUrl = widget.courseDetails['intro_video'];
    _videoPlayerController1 = VideoPlayerController.network(
        videoUrl);
    _chewieController = ChewieController(
      videoPlayerController: _videoPlayerController1,
      aspectRatio: 3 / 2,
      autoInitialize: true,
    );
  }

void dispose() {
    _videoPlayerController1.dispose();
    _chewieController.dispose();
    super.dispose();
  }

Flexible(
                child: Center(
                  child: Chewie(
                    controller: _chewieController,
                  ),
                ),
              )
```

Getting this error log on Android Platform: 
```
E/ExoPlayerImplInternal(21279): Source error.
E/ExoPlayerImplInternal(21279): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://159.65.154.185:89/storage/1583925566_sample-video.mp4
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(21279): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(21279): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(21279): 	at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(21279): Caused by: java.io.IOException: Cleartext HTTP traffic to 159.65.154.185 not permitted
E/ExoPlayerImplInternal(21279): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal(21279): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
E/ExoPlayerImplInternal(21279): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal(21279): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(21279): 	... 6 more
E/flutter (21279): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://159.65.154.185:89/storage/1583925566_sample-video.mp4, null)
E/flutter (21279): #0      ChewieController._initialize (package:chewie/src/chewie_player.dart:291:7)
E/flutter (21279): <asynchronous suspension>
E/flutter (21279): #1      new ChewieController (package:chewie/src/chewie_player.dart:197:5)
E/flutter (21279): #2      _CourseDetailScreenState.initState (package:academe/screens/course_detail_screen.dart:81:25)
E/flutter (21279): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (21279): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (21279): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (21279): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (21279): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (21279): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (21279): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (21279): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (21279): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (21279): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (21279): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (21279): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (21279): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (21279): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (21279): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (21279): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (21279): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (21279): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (21279): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (21279): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (21279): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (21279): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (21279): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (21279): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (21279): #4
```

**Comment by SametSahin10** [comment]
Directly from the documentation in this [link](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted):

> Starting with Android 9 (API level 28), cleartext support is disabled by default.

Add this line to application element at AndroidManifest.xml
`android:usesCleartextTraffic="true"`
Refer to [this](https://stackoverflow.com/a/50834600/6753606) Stackoverflow answer for more detailed information.

**Comment by swapnilshah09** [comment]
Thanks, @SametSahin10 that was very helpful.
