### ISSUE TITLE
IOS Url Video Error when no file extension?

### ISSUE THREAD

**Issue by acavazos1982** [brianegan/chewie#306]
Hi, i have a server that uses tokens to protect streams the files dont have a file extension and it errors out, im running on IOS, heres the log. PS. It works on vlc player.

2020-05-07 08:42:43.781408-0500 Runner[2273:535263] flutter: VideoUrl: https://fs1.firemedia.mx/archi5/a9/a9ed1111885007b672650f226cacf9c9?st=veDg1jnZRHZoURJihVBxZg&e=1588869689
2020-05-07 08:42:49.467192-0500 Runner[2273:535263] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null)
2020-05-07 08:43:12.967035-0500 Runner[2273:535263] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_duration' was called on null.
Receiver: null
Tried calling: _duration
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Duration.> (dart:core/duration.dart:163:61)
#2      VideoPlayerController.seekTo (package:video_player/video_player.dart:420:18)
#3      _ChewieDemoState.build.<anonymous closure>.<anonymous closure> (package:purple/VideoPlayer.dart:118:49)
#4      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#5      _ChewieDemoState.build.<anonymous closure> (package:purple/VideoPlayer.dart:115:23)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:855:36)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#23     _rootRunUnary (dart:async/zone.dart:1196:13)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#26     _invoke1 (dart:ui/hooks.dart:291:10)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:200:5)
2020-05-07 08:43:18.199093-0500 Runner[2273:535263] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_duration' was called on null.

**Comment by Nico04** [comment]
Same issue here.
Reported since 2020, any news ?

**Comment by Mohsin0344** [comment]
The issue lies with the Flutter cache manager. If you first cache the video and then provide the file to Chewie, Flutter cache manager adds ".bin" to the video files, which is not a valid video extension.
