### ISSUE TITLE
I get this error when i change landscape to Portrait.

### ISSUE THREAD

**Issue by PreviousTlx** [brianegan/chewie#330]
I get this error when i change landscape to Portrait and notice native(Android) change screen orientation.How can i solve it? Thanks!

PlatformException(no_activity, wakelock requires a foreground activity, null)

**Comment by PreviousTlx** [comment]
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(no_activity, wakelock requires a foreground activity, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      Wakelock.disable (package:wakelock/wakelock.dart:27:16)
    #4      ChewieState._pushFullScreenWidget (package:chewie/src/chewie_player.dart:147:14)
    #5      _rootRunUnary (dart:async/zone.dart:1192:38)
    #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
    #12     _rootRun (dart:async/zone.dart:1184:13)
    #13     _CustomZone.run (dart:async/zone.dart:1077:19)
    #14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
