### ISSUE TITLE
Video is not playing after 12 videos

### ISSUE THREAD

**Issue by falguni0314** [brianegan/chewie#361]
Hi, I am using chewie inside page view to play video dynamically but getting bellow error, kindly help.

I/ExoPlayerImpl(32193): Init ae605c1 [ExoPlayerLib/2.9.6] [OnePlus7TPro, HD1911, OnePlus, 29]
I/DpmTcmClient(32193): RegisterTcmMonitor from: $Proxy0
D/AudioTrack(32193): ClientUid 10500 AudioTrack::pause
D/MediaCodec(32193):  name = OMX.qcom.video.decoder.avc
I/OMXClient(32193): IOmx service obtained
E/ACodec  (32193): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (32193): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(32193): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(32193): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(32193): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer(32193): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(32193): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer(32193): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer(32193): 	at android.media.MediaCodec.<init>(MediaCodec.java:1876)
W/MediaCodecRenderer(32193): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1848)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(32193): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(32193): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(32193): 	at android.os.Looper.loop(Looper.java:214)
W/MediaCodecRenderer(32193): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(32193): Playback error.
E/ExoPlayerImplInternal(32193): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [480, 854, -1.0], [-1, -1])
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(32193): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(32193): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(32193): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(32193): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [480, 854, -1.0], [-1, -1])
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(32193): 	... 9 more
E/ExoPlayerImplInternal(32193): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(32193): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(32193): 	at android.media.MediaCodec.<init>(MediaCodec.java:1876)
E/ExoPlayerImplInternal(32193): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1848)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal(32193): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(32193): 	... 10 more

**Comment by aytunch** [comment]
@falguni0314 Do you dispose the videos that are not being shown? It can be a memory issue. Can you share a code snippet?

**Comment by falguni0314** [comment]
Yes it was a memory related issue, thanks for your reply.

But we are facing below issue:

1. Videos are playing on background on press of home button.

2. Buffering is always returning false.
