### ISSUE TITLE
Android release issue

### ISSUE THREAD

**Issue by Joyker** [brianegan/chewie#368]
Hello, there is a problem. In debug everythinng fine, but in release i got half screen grey and audio.
  Flutter (Channel stable, 1.20.2)
  chewie: 0.9.10
  video_player: 0.10.12+5

in console:
E/flutter (18918): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'contains' was called on null.
E/flutter (18918): Receiver: null
E/flutter (18918): Tried calling: contains()
E/flutter (18918): #0      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2151)
E/flutter (18918): #1      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2505)
E/flutter (18918): #2      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:773)
E/flutter (18918): #3      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2500)
E/flutter (18918): #4      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:411)
E/flutter (18918): #5      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #6      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #8      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #10     RenderClipRRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1431)
E/flutter (18918): #11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #13     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #17     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3124)
E/flutter (18918): #18     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2505)
E/flutter (18918): #19     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:773)
E/flutter (18918): #20     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2500)
E/flutter (18918): #21     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:599)
E/flutter (18918): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #23     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #25     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #26     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2543)
E/flutter (18918): #27     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:773)
E/flutter (18918): #28     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2537)
E/flutter (18918): #29     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2523)
E/flutter (18918): #30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #31     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2543)
E/flutter (18918): #32     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:773)
E/flutter (18918): #33     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2537)
E/flutter (18918): #34     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2523)
E/flutter (18918): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #39     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124)
E/flutter (18918): #40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2152)
E/flutter (18918): #41     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3124)
E/flutter (18918): #42     RenderProxyBoxMixin.hitTestChildren (pa

Thanks in advance

**Comment by ahmedJD** [comment]
same problem did you find a solution

**Comment by Joyker** [comment]
> same problem did you find a solution
Can you share code with problem?

**Comment by al-sadi** [comment]
Same here .. I got to make the example work on my device (although the [current version of the example](https://github.com/brianegan/chewie/blob/94d4e717d44c9954c59fd191d5d3d731057e4c75/example/lib/app/app.dart) has issues), but when I build a release apk, the example does not work anymore.

**Comment by shivaRamdeen** [comment]
same issue here. Any solution?

**Comment by Siddharth2212** [comment]
Any resolution?
