### ISSUE TITLE
Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error

### ISSUE THREAD

**Issue by knixer** [brianegan/chewie#420]
The error message comes up sometimes when I try to access a video displayed in my Flutter application. I am using Chewie (https://pub.dev/packages/chewie) when rendering my videos. The video is an mp4 file and works most of the time.

Full error message:
`Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1280, 720, 29.973475], [-1, -1]), format_supported=YES`

It is not evident to me how the problem can be reproduced because it happens arbitrarily.

I don't know the ExoPlayer version number. But I downloaded Chewie and video_player yesterday so I should have the latest. If I can find the version number in the bug report let me know. The expected behavior is no error message and a working video
Device: Samsung SM-J105H
Android version 5.1.1

Here is info from the bug report. I do not know what information is of use...

```
01-18 12:22:38.159   770  1228 D InputMethodManagerService: windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
01-18 12:22:38.169  1691  1691 D InputMethodFrameWorkUtils: InputMethodSubtype is found as local:sv
01-18 12:22:38.169  1691  1691 D InputMethodFrameWorkUtils: InputMethodSubtype is set as local:sv
01-18 12:22:38.169  9355  9400 I flutter : singleTestscreenItem :: Chewie Error: Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1280, 720, 29.973475], [-1, -1]), format_supported=YES
01-18 12:22:38.169  1691  1691 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1748 android.content.ContextWrapper.sendBroadcast:392 com.sec.android.inputmethod.inputmethodframework.InputMethodFrameWorkUtils.setCurrentInputMethodSubtype:49 com.ime.framework.common.InputManagerImpl.finishInput:5031 com.sec.android.inputmethod.SamsungKeypad.onFinishInput:682 
01-18 12:22:38.179 14816 14816 W linker  : libliger.so: unused DT entry: type 0x6ffffef5 arg 0x4b4c
01-18 12:22:38.179  1691  1691 D SamsungIME: onStartInput: No inputType, No imeOption, isInputViewShown = false, isExtractViewShown = false, isShowInputRequested = false, isConfigChanged = false
01-18 12:22:38.179  9497  9497 D StatusBar: getNumberOfActiveSim: 1
01-18 12:22:38.179   770   848 V WindowStateAnimator: Finishing drawing window Window{c0d5266 u0 d0 SurfaceView}: mDrawState=READY_TO_SHOW
01-18 12:22:38.189 14816 14816 W linker  : libliger.so: unused DT entry: type 0x6ffffffe arg 0x4b0c
```

**Comment by gj2569355373** [comment]
Please change the video source
更换视频源

**Comment by knixer** [comment]
Same result.

Error log: 
```
E/ExoPlayerImplInternal(  958):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1280, 720, 29.973475], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(  958):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(  958):       at android.os.Looper.loop(Looper.java:145)
E/ExoPlayerImplInternal(  958):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(  958):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.h264.decoder, Format(1, null, null, video/avc, null, -1, null, [1280, 720, 29.973475], [-1, -1])
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(  958):       ... 3 more
E/ExoPlayerImplInternal(  958):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc03
E/ExoPlayerImplInternal(  958):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(  958):       at android.media.MediaCodec.configure(MediaCodec.java:577)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
E/ExoPlayerImplInternal(  958):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
E/ExoPlayerImplInternal(  958):       ... 10 more
```
> Please change the video source
> 更换视频源

**Comment by nstrelow** [comment]
Chewie is NOT a video player, but a UI for the video_player package.

Please report the error there.
