### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by harshapulikollu** [brianegan/chewie#65]
I have a grid view in which I have chewie under gesture detector when on tap it redirects to new page and video have to play there with other details related to that video.  But unfortunately when I tried to play the video I'm getting this playback error by the player.
```
E/ExoPlayerImplInternal(23535): Playback error.
E/ExoPlayerImplInternal(23535): com.google.android.exoplayer2.ExoPlaybackException
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/ExoPlayerImplInternal(23535): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(23535): 	at android.os.Looper.loop(Looper.java:163)
E/ExoPlayerImplInternal(23535): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(23535): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(23535): 	... 9 more
E/ExoPlayerImplInternal(23535): Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(23535): 	at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(23535): 	at android.media.MediaCodec.configure(MediaCodec.java:1884)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:450)
E/ExoPlayerImplInternal(23535): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:418)
E/ExoPlayerImplInternal(23535): 	... 8 more
```

**Comment by Sub6Resources** [comment]
Looks like an issue with the video_player plugin, so not much we can do. I suggest reporting it there.
