### ISSUE TITLE
rotate the phone cause bug

### ISSUE THREAD

**Issue by iptton** [brianegan/chewie#69]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.10-pre.2, on Mac OS X 10.14.2 18C48a, locale zh-Hans-HK)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

```
/flutter (13913): setState() or markNeedsBuild() called during build.
E/flutter (13913): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (13913): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (13913):   Overlay-[LabeledGlobalKey<OverlayState>#09ad3](state: OverlayState#efd86(entries: [OverlayEntry#f3def(opaque: false; maintainState: false), OverlayEntry#32059(opaque: false; maintainState: true), OverlayEntry#736b1(opaque: false; maintainState: false), OverlayEntry#336a0(opaque: false; maintainState: true)]))
E/flutter (13913): The widget which was currently being built when the offending call was made was:
E/flutter (13913):   Chewie(dirty, state: _ChewiePlayerState#7d8d0)
E/flutter (13913): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3485:11)
E/flutter (13913): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
E/flutter (13913): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
E/flutter (13913): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
E/flutter (13913): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
E/flutter (13913): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:185:11)
E/flutter (13913): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:861:11)
E/flutter (13913): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1560:11)
E/flutter (13913): #8      _ChewiePlayerState._pushFullScreenWidget (package:custom_chewie/src/custom_chewie_player.dart:233:33)
```

**Comment by Sub6Resources** [comment]
Which device are you using?

**Comment by cbenhagen** [comment]
You are using a fork of chewie. Unfortunately @bostrot did not enable issues on his repository yet.
